version: '3.8'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: app-container
    restart: always
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx-container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d